image:
  - Ubuntu
  - Visual Studio 2017
# Build script
init:
  - git config --global core.autocrlf true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    test: off      
    build_script:
      - cd build
      - dotnet --info
      - cd /usr/share/dotnet/sdk
      - ls -d * | grep -v ^2.1.4$ | sudo xargs rm -r
      - ls -l
      - cd -
      - chmod +xxx ./build.sh
      - dotnet --info
      - ./build.sh --target="AppVeyor" --configuration=Release --UploadCoverageReport=False
  -
    matrix:
      only:
        - image: Visual Studio 2017
    test: off
    build_script:
      - cd Build
      - dotnet --info
      - ps: >-
          .\build.ps1 --target="AppVeyor" --configuration=Release --UploadCoverageReport=True
          
      
# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - dev
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - Build/tools -> Build/build.cake
