image:
  - Visual Studio 2017
  - Ubuntu
# Build script
init:
  - git config --global core.autocrlf true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
for:
  -
    matrix:
      only:
        - image: Ubuntu
          
    build_script:
      - cd build
      - ls -l
      - dotnet --version
      - chmod +xxx ./build.sh
      - ./build.sh --target="AppVeyor" --configuration=Release
  -
    matrix:
      only:
        - image: Visual Studio 2017
    build_script:
      - cd Build
      - ps: >-
          echo "Platform: $ENV:OS dotnet version: $(dotnet --version)"
      - ps: .\build.ps1 -Configuration Release -Target AppVeyor
# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - dev
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - Build/tools -> Build/build.cake
