image:
  - Ubuntu
  - Visual Studio 2017
# Build script
init:
  - git config --global core.autocrlf true
for:
  -
    matrix:
      only:
        - image: Ubuntu
    test: off      
    build_script:
      - cd build
      - chmod +xxx ./build.sh
      - ./build.sh --target="AppVeyor" --configuration=Release
  -
    matrix:
      only:
        - image: Visual Studio 2017
    test: off
    build_script:
      - cd Build
      - ps: >-
          .\build.ps1 --target="AppVeyor" --configuration=Release
          
      
# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - dev
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - Build/tools -> Build/build.cake
